services:
#####___ DATABASES___#####
#POSTGRES
  menu-management-service-db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: storage
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5432:5432

  order-management-service-db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: storage
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5433:5432

  payment-service-db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: storage
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5434:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9001:8080
#NOSQL
  notification-service-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: storage
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9002:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@notification-service-db:27017/storage?authSource=admin
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass

#####___ APPLICATION___#####
#  application:
#    image: menu-management-service-image
#    restart: always
#    ports:
#      - 8080:8082
